# Generated by Django 5.0 on 2024-02-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reason',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
