# Generated by Django 5.0 on 2024-02-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_notification_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_details',
            name='threshold',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.hospital_details'),
        ),
        migrations.AddField(
            model_name='hospital_details',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital_details',
            name='threshold',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
