# Generated by Django 5.0 on 2024-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_blood_details_threshold_hospital_details_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_details',
            name='size',
        ),
        migrations.RemoveField(
            model_name='hospital_details',
            name='threshold',
        ),
        migrations.AlterField(
            model_name='blood_details',
            name='days',
            field=models.DateField(default=None, null=True),
        ),
    ]
