# Generated by Django 5.0 on 2024-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_hospital_details_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_details',
            name='days',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
