# Generated by Django 5.0 on 2024-03-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_blood_details_donation_date_blood_details_valid_till'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_details',
            name='days',
        ),
    ]
