# Generated by Django 5.0 on 2024-03-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_blood_details_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_details',
            name='donation_date',
        ),
        migrations.RemoveField(
            model_name='blood_details',
            name='valid_till',
        ),
        migrations.AddField(
            model_name='blood_details',
            name='days',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
