# Generated by Django 5.0 on 2024-03-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_remove_blood_details_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_details',
            name='days',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
