# Generated by Django 5.0 on 2024-03-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_blood_details_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_details',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
