# Generated by Django 5.0 on 2024-03-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_remove_blood_details_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_details',
            name='donation_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
