# Generated by Django 5.0 on 2024-03-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_blood_details_donation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_details',
            name='donation_date',
        ),
        migrations.RemoveField(
            model_name='blood_details',
            name='valid_days',
        ),
        migrations.RemoveField(
            model_name='blood_details',
            name='valid_till',
        ),
        migrations.AddField(
            model_name='blood_details',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
