# Generated by Django 5.0 on 2024-03-14 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_remove_blood_details_donation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='request_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donating_hospital', models.CharField(max_length=354)),
                ('blood_type', models.CharField(max_length=345)),
                ('amount', models.IntegerField()),
                ('message', models.CharField(max_length=546)),
                ('is_accepted', models.BooleanField()),
                ('is_confirmed', models.BooleanField()),
                ('requesting_hospital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
