# Generated by Django 5.0 on 2024-03-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_request_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligible_hospitals',
            name='requested_amount',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
