# Generated by Django 5.0 on 2024-03-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_eligible_hospitals_total_wt'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligible_hospitals',
            name='available_blood_type',
            field=models.CharField(default=None, max_length=624, null=True),
        ),
    ]
