# Generated by Django 5.0 on 2024-03-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_eligible_hospitals_available_blood_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_details',
            name='days',
        ),
        migrations.AddField(
            model_name='blood_details',
            name='donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blood_details',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
