# Generated by Django 5.0 on 2024-03-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_remove_blood_details_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_details',
            name='remaining_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
