# Generated by Django 5.0 on 2024-03-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_blood_details_remaining_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='remaining_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
