# Generated by Django 5.0 on 2024-04-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_notification_amount_notification_remaining_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_list',
            name='total_wt',
            field=models.FloatField(default=None, null=True),
        ),
    ]
