# Generated by Django 5.0 on 2024-04-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_request_list_total_wt'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligible_hospitals',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='eligible_hospitals',
            name='is_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='eligible_hospitals',
            name='is_sent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
