# Generated by Django 5.0 on 2024-04-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_request_list_available_blood_type_blood_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_confirmed',
            name='reason',
            field=models.CharField(default=None, max_length=546, null=True),
        ),
    ]
