# Generated by Django 5.0 on 2024-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_remove_blood_send_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_list',
            name='available_amount',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
