# Generated by Django 5.0 on 2024-04-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_blood_details_hospital1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_details',
            name='hospital1',
        ),
    ]
